### ISSUE TITLE
Graphics artifacting, glitchy, and distorted

### ISSUE THREAD

**Issue by MEMESCOEP** [HailToDodongo/tiny3d#28]
I've been having a lot of trouble with graphical artifacting and general bugginess / distortion lately, and I was wondering if it was something I'm doing wrong. I noticed that the more times I use `rdpq_text_printf`, the more glitchy things become until I models just become lines.

Here's a sample of the issue:

https://github.com/user-attachments/assets/c2c0bb67-a0e0-4a37-aad2-3eda1d65a162

And here's my code so far (pastebin):
[main.c](https://pastebin.com/E14ufmhA)
[N64GameEngine.c](https://pastebin.com/bxcEi4aC)
[N64GameEngine.h](https://pastebin.com/niKUH8Yn)
[MathUtils.h](https://pastebin.com/A5rTZ9L4)

Am I doing something I shouldn't be?

**Comment by HailToDodongo** [comment]
Solved in discord here: https://discord.com/channels/205520502922543113/1307272063194759208
issues was a near-plane that was too close, loosing precision
